//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servicios
    {
        public int Codigo { get; set; }
        public string Servicios1 { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> Precio { get; set; }
        public string Observacion { get; set; }
        public string FechaRegistro { get; set; }
    }
}
