//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLConexion
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehiculo
    {
        public string Patente { get; set; }
        public string Marca { get; set; }
        public string Color { get; set; }
        public string Modelo { get; set; }
        public string Motor { get; set; }
        public string Chasis { get; set; }
        public Nullable<int> Metraje { get; set; }
        public Nullable<int> Anio { get; set; }
        public Nullable<int> Conductor_id { get; set; }
    }
}
